# Generated by Django 3.1.7 on 2021-04-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=16)),
                ('username', models.TextField(max_length=16, unique=True)),
                ('password', models.TextField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(max_length=64)),
                ('category', models.CharField(max_length=6)),
                ('region', models.CharField(max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.authors')),
            ],
        ),
    ]
