# Generated by Django 3.1.7 on 2021-04-07 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='password',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='username',
        ),
        migrations.AddField(
            model_name='authors',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
